from params import P, Params
PARAMS = Params([
    P('N_ps', 'P%InitPower%nn', 'number of spectra', type=int, default=1),
    P('omegab', 'P%omegab', 'Omega Baryon', default=0.0464),
    P('omegac', 'P%omegac', 'Omega Dark Mater', default=0.235),
    P('omegav', 'P%omegav', 'Omega Vaccum', default=0.7186),
    P('omegan', 'P%omegan', 'Omega Neutrino', default=0),
    P('omegak', 'P%omegak', 'Omega Curvature', default=0),
    P('H0',     'P%H0', 'Hubble Parameter in Km/s/Mpc', default=70.),
    P('TCMB',   'P%TCMB', 'CMB Temperature in K', default=2.73),
    P('yhe',    'P%yhe', 'helium fraction', default=0.24),
    P('NonLinear', 'P%NonLinear', 
        'Method of Non Linear evolution, 0(None), 1(PK), 2(Lens)', 
        default=0, type=int),
    P('N_nu_massless', 'P%Num_Nu_massless', 'neutrino massless', default=3.04),
    P('N_nu_massive', 'P%Num_Nu_massive', 'neutrino masssive', default=0),
    P('Reion', 'P%Reion%Reionization', 'reionization', type=bool, default=True),
    P('z_reion', 'P%Reion%redshift', 'reionization redshift', default=10.36),
    P('f_reion', 'P%Reion%fraction', 'reionization fraction'),
    P('ReionUseOpticalDepth', 'P%Reion%use_optical_depth', 
        'reionization use optical depth', type=bool, default=False),
    P('tau_reion', 'P%Reion%optical_depth', 'reionization optical depth',
        default=0.0851),
    P('ScalarICMode', 'P%Scalar_initial_condition', 
        'Scalar IC mode: 0=vector, 1=adiabatic 2=iso_CDM 3=ISO_Baryon'
        '4=ISO_neutrino, 5=iso_neutrino_vel', type=int, default=1),
    P('WantScalars', 'P%WantScalars', 'use scalar', type=bool, default=True),
    P('ScalarPowerAmp', 'P%InitPower%ScalarPowerAmp', 
            'Scalar amp related to sigma8 but need iteration!',
            default=2.1e-9),
    P('n_s', 'P%InitPower%an', 'scalar index', default=0.971),
    P('K_s', 'P%InitPower%n_run', 'scalar running', default=0),
    P('WantTensors', 'P%WantTensors', 'use tensor', type=bool, default=False),
    P('n_t', 'P%InitPower%ant', 'tensor index', default=0),
    P('ts', 'P%InitPower%rat', 'tensor ratio', default=0),
    P('lAccuracyBoost', 'lAccuracyBoost', 'l accuracy boost', default=1.0),
    P('lSampleBoost', 'lSampleBoost', 'l sample boost', default=1.0),
    P('w_lam', 'w_lam', 'w_lam', default=-1.0),
    P('cs2_lam', 'cs2_lam', 'cs2_lam', default=1.0),
    P('AccuracyBoost', 'AccuracyBoost', 'Accuracy Boost', default=1.0),
    P('w_perturb', 'w_perturb', 'w_perturb', type=bool, default=False),
    P('DoLensing', 'P%DoLensing', 'Do Lensing', type=bool, default=False),
])


